"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Button, Flex, Grid } from "@tremor/react";
import { useState } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Election tools by Civera",
//   description: "Generated by create next app",s
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [darkMode, setDarkMode] = useState(false);
  const toggleTheme = () => {
    setDarkMode(!darkMode);
  };

  return (
    <html lang="en">
      <body
        className={`App ${darkMode ? "dark" : ""} ${
          inter.className
        } bg-white dark:bg-gray-900`}
        style={{ padding: 40 }}
      >
        <div className={`container mx-auto ${darkMode ? "dark" : ""}`}>
          <Flex justifyContent="end" className="mb-4">
            <Button variant="secondary" onClick={toggleTheme}>
              {darkMode ? "Light" : "Dark"}
            </Button>
          </Flex>
          {children}
        </div>
      </body>
    </html>
  );
}
